include:
  - infra/nginx/compose.nginx.yml
  - infra/redis/compose.redis.yml
  - infra/monitoring/prometheus/compose.prometheus.yml
  - infra/monitoring/grafana/compose.grafana.yml
  - url-shortener/compose.shortener.yml

networks:
  shortener-network:
    driver: bridge